import browser_cookie3
import time

cookies = browser_cookie3.chrome()

with open('youtube_cookies.txt', 'w') as f:
    f.write("# Netscape HTTP Cookie File\n")
    f.write("# This file was generated by a script. Edit at your own risk.\n\n")
    
    for cookie in cookies:
        if '.youtube.com' in cookie.domain:
            secure = "TRUE" if cookie.secure else "FALSE"
            expiry = str(int(cookie.expires)) if cookie.expires else str(int(time.time() + 365*24*60*60))
            
            f.write(f"{cookie.domain}\tTRUE\t{cookie.path}\t{secure}\t{expiry}\t{cookie.name}\t{cookie.value}\n")
